---
driver:
  name: vagrant
  ## enable to interact with the test app on port 8080 of host machine
  # network:
  #   - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # overriding for now do to an issue with ubuntu-16.04 bento box failing to install chef
  # because of a dpkg lock caused by unattended upgrade on bootup
  # https://github.com/chef/bento/issues/609
  chef_omnibus_url: https://gist.githubusercontent.com/atheiman/d13b52d594731b35ee49effac74dabc7/raw/6d22d4deda5f8d4e4d22ab57b2538fc7a5beaf14/install.sh

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[simple_passenger::default]
    attributes:
      passenger:
        git_repo: https://github.com/atheiman/simple-sinatra.git
