source 'https://rubygems.org'

gem 'rake', '~> 11.2'
gem 'berkshelf', '~> 4.3'
gem 'stove', '~> 4.1'
gem 'test-kitchen', '~> 1.10'
gem 'kitchen-vagrant', '~> 0.20'
gem 'chefspec', '~> 4.7'
gem 'foodcritic', '~> 6.3'
gem 'rubocop', '~> 0.41'
gem 'kitchen-docker', '~> 2.1.0'
