name 'simple_passenger'
maintainer 'Austin Heiman'
maintainer_email 'atheimanksu@gmail.com'
license 'all_rights'
description 'Chef cookbook to deploy a rack based Ruby web application with Passenger standalone'
long_description 'Chef cookbook to deploy a rack based Ruby web application with Passenger standalone'
version '0.3.0'

depends 'logrotate', '~> 1.9.2'
depends 'build-essential', '~> 6.0.0'
depends 'apt', '~> 4.0.1'
depends 'ruby_build', '~> 0.8.0'
